apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: spring-boot-skaffold-example-image
      context: .
      custom:
        buildCommand: "./mvnw clean package && docker build -t $IMAGE ."
        dependencies:
          paths:
            - "target/classes"
            - "pom.xml"
            - "Dockerfile"
            - "skaffold.yaml"

deploy:
  kubeContext: minikube
  helm:
    releases:
      - name: test
        chartPath: ./k8s/helm/chart
        version: 2
        values:
          image: spring-boot-skaffold-example-image
    flags:
      upgrade:
        - "--install"
profiles:
  - name: dev
    build:
      local:
        push: false