apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot
spec:
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot
    spec:
      containers:
        - name: boot
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
